# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# INTERNAL USE ONLY
# Refer to https://github.com/hashicorp/tfc-workflows-github for available actions
name: "Test Workspace Output"
description: "Returns JSON array of the latest state-version output(s) for a given Terraform Cloud workspace."

inputs:
  # global flags
  hostname:
    required: false
    description: "The hostname of a Terraform Enterprise installation, if using Terraform Enterprise. Defaults to Terraform Cloud (app.terraform.io) if `TF_HOSTNAME` environment variable is not set."
    default: ""
  token:
    required: false
    description: "The token used to authenticate with Terraform Cloud. Defaults to reading `TF_API_TOKEN` environment variable"
    default: ""
  organization:
    required: false
    description: "The name of the organization in Terraform Cloud. Defaults to reading `TF_CLOUD_ORGANIZATION` environment variable"
    default: ""
  # required
  workspace:
    required: true
    description: "The name of the workspace to create the new configuration version in."

outputs:
  status:
    description: "The result of the operation. Possible values are `Success`, `Error` or `Timeout`"
  outputs:
    description: "JSON array containing the workspace outputs. Sensitive values are redacted."

runs:
  using: docker
  image: ../../../Dockerfile
  args:
    - tfci
    ## global flags
    - -hostname=${{ inputs.hostname }}
    - -token=${{ inputs.token }}
    - -organization=${{ inputs.organization }}
    ## command arguments
    - workspace ouput list
    - -workspace=${{ inputs.workspace }}
