---
name: e2e

on:
  schedule:
    - cron: 25 6 * * *

jobs:
  initialize-tfc-resources:
    runs-on: "ubuntu-latest"
    env:
      TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
    defaults:
      run:
        working-directory: .github/terraform/tfe
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - uses: hashicorp/setup-terraform@v1
        id: terraform-setup
        with:
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform create CI workspaces
        run: |
          terraform apply \
          -var "organization=$TF_CLOUD_ORGANIZATION" \
          --auto-approve -input=false

  speculative-run:
    runs-on: "ubuntu-latest"
    needs: initialize-tfc-resources
    env:
      TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_LOG: DEBUG
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - uses: ./.github/actions/test-upload-configuration
        id: upload
        with:
          workspace: ci-workspace-test
          directory: .github/terraform/workspace
          speculative: true

      - uses: ./.github/actions/test-create-run
        id: create-run
        with:
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
          workspace: ci-workspace-test
          plan_only: true

      - uses: ./.github/actions/test-plan-output
        id: plan
        with:
          plan: ${{ steps.create-run.outputs.plan_id }}

      - name: Echo Plan Output
        run: |
          echo "Add: ${{ steps.plan.outputs.add}}"
          echo "Change: ${{ steps.plan.outputs.change}}"
          echo "Destroy: ${{ steps.plan.outputs.destroy}}"

  destroy-tfc-resources:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: .github/terraform/tfe
    env:
      TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_WORKSPACE: ${{ vars.TF_WORKSPACE }}
    needs: speculative-run
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - uses: hashicorp/setup-terraform@v1
        id: terraform-setup
        with:
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform destroy CI workspaces
        run: |
          terraform destroy \
          -var "organization=$TF_CLOUD_ORGANIZATION" \
          --auto-approve -input=false
